<?php
/**
 * IUBENDA - Privacy Policy Generator
 *
 * @author     iubenda <info@iubenda.com>
 * @category   legal
 * @package    Iubenda_Policy
 * @copyright  Copyright (c) 2003-2012 iubenda srl (http://www.iubenda.com)
 * @license    http://www.gnu.org/licenses/gpl-3.0.html (GPL)
 */
?>
<?php if (Mage::helper('iubenda_policy')->isEmbeddingEnabled() && Mage::helper('iubenda_policy')->embedViaBadge()): ?>
	<?php echo $this->getEmbeddingCode() ?>
<?php endif; ?>